# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billboard_id', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=30)),
                ('height', models.DecimalField(decimal_places=3, max_digits=30)),
                ('width', models.DecimalField(decimal_places=3, max_digits=30)),
                ('area_sr', models.DecimalField(decimal_places=3, max_digits=30)),
                ('availablity', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('backlight', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
    ]
